package com.nsmm.esg.scopeservice.config;

import com.nsmm.esg.scopeservice.entity.FuelData;
import com.nsmm.esg.scopeservice.entity.enums.EmissionActivityType;
import com.nsmm.esg.scopeservice.entity.enums.FuelCategory;
import com.nsmm.esg.scopeservice.entity.enums.SubcategoryType;
import com.nsmm.esg.scopeservice.repository.FuelDataRepository;
import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;

/**
 * 연료 마스터 데이터 초기화
 * frontend-p3/src/constants/fuel-data.ts의 모든 데이터를 기반으로 생성
 */
@Component
@Slf4j
@RequiredArgsConstructor
public class FuelDataInitializer {

    private final FuelDataRepository fuelDataRepository;

    @PostConstruct
    @Transactional
    public void initializeFuelData() {
        log.info("연료 마스터 데이터 초기화 시작...");

        // 기존 데이터 확인
        long count = fuelDataRepository.count();

        if (count > 0) {
            log.info("연료 마스터 데이터가 이미 존재합니다. ({}개) 초기화를 건너뜁니다.", count);
            return;
        }

        // fuel-data.ts 기반으로 모든 연료 데이터 생성
        createAllFuelData();

        log.info("연료 마스터 데이터 초기화 완료!");
    }

    private void createAllFuelData() {
        log.info("전체 연료 데이터 생성 중...");

        // === 액체연료 (Liquid Petroleum) ===
        createLiquidPetroleumFuels();

        // === 기체연료 (Gaseous) ===
        createGaseousFuels();

        // === 고체연료 (Solid) ===
        createSolidFuels();

        // === 기타 화석연료 (Other Fossil) ===
        createOtherFossilFuels();

        // === 바이오매스 (Biomass) ===
        createBiomassFuels();

        // === 전력 (Electricity) ===
        createElectricityData();

        // === 스팀 (Steam) ===
        createSteamData();

        long totalCount = fuelDataRepository.count();
        log.info("총 {}개의 연료 데이터가 생성되었습니다.", totalCount);
    }

    // saveFuelData 헬퍼 메서드 추가
    private void saveFuelData(FuelData fuelData) {
        fuelDataRepository.save(fuelData);
        log.debug("연료 데이터 저장: {} - {}", fuelData.getFuelId(), fuelData.getFuelName());
    }

    // === 액체연료 생성 메서드 ===
    private void createLiquidPetroleumFuels() {
        log.info("액체연료 데이터 생성 중...");
        
        // 원유 (잘려있던 데이터 복원)
        saveFuelData(FuelData.builder()
                .fuelId("CRUDE_OIL")
                .fuelName("원유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("44.9"))
                .ncv(new BigDecimal("42.2"))
                .co2Factor(new BigDecimal("73300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 오리멀전
        saveFuelData(FuelData.builder()
                .fuelId("ORIMULSION")
                .fuelName("오리멀전")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("27.5"))
                .co2Factor(new BigDecimal("77000"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 천연가스액
        saveFuelData(FuelData.builder()
                .fuelId("NGL")
                .fuelName("천연가스액")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("44.2"))
                .co2Factor(new BigDecimal("64200"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 휘발유
        saveFuelData(FuelData.builder()
                .fuelId("GASOLINE")
                .fuelName("휘발유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.MOBILE_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("32.6"))
                .ncv(new BigDecimal("30.3"))
                .co2Factor(new BigDecimal("69300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .mobileCo2Factor(new BigDecimal("69300"))
                .mobileCh4Factor(new BigDecimal("25"))
                .mobileN2oFactor(new BigDecimal("8.0"))
                .hasMobileFactors(true)
                .build());

        createRemainingLiquidFuels();
    }

    private void createRemainingLiquidFuels() {
        // 항공유
        saveFuelData(FuelData.builder()
                .fuelId("AVIATION_GASOLINE")
                .fuelName("항공유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("36.5"))
                .ncv(new BigDecimal("34.1"))
                .co2Factor(new BigDecimal("70000"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 제트용 가솔린(IP-8)
        saveFuelData(FuelData.builder()
                .fuelId("JET_FUEL_GASOLINE")
                .fuelName("제트용 가솔린(IP-8)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("44.3"))
                .co2Factor(new BigDecimal("70000"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 제트용 등유(JET A-1)
        saveFuelData(FuelData.builder()
                .fuelId("JET_FUEL_KEROSENE")
                .fuelName("제트용 등유(JET A-1)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("44.1"))
                .co2Factor(new BigDecimal("71500"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 등유 (실내등유 - 이동연소용)
        saveFuelData(FuelData.builder()
                .fuelId("KEROSENE")
                .fuelName("실내등유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.MOBILE_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("36.8"))
                .ncv(new BigDecimal("34.3"))
                .co2Factor(new BigDecimal("71900"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .mobileCo2Factor(new BigDecimal("71900"))
                .mobileCh4Factor(BigDecimal.ZERO)
                .mobileN2oFactor(BigDecimal.ZERO)
                .hasMobileFactors(true)
                .build());

        // 혈암유
        saveFuelData(FuelData.builder()
                .fuelId("SHALE_OIL")
                .fuelName("혈암유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("38.1"))
                .co2Factor(new BigDecimal("73300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 경유
        saveFuelData(FuelData.builder()
                .fuelId("DIESEL")
                .fuelName("가스/디젤 오일(경유)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.MOBILE_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("37.7"))
                .ncv(new BigDecimal("35.3"))
                .co2Factor(new BigDecimal("74100"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .mobileCo2Factor(new BigDecimal("74100"))
                .mobileCh4Factor(new BigDecimal("3.9"))
                .mobileN2oFactor(new BigDecimal("3.9"))
                .hasMobileFactors(true)
                .build());

        // 보일러등유 (고정연소용 - 모바일 배출계수 포함)
        saveFuelData(FuelData.builder()
                .fuelId("BOILER_KEROSENE")
                .fuelName("보일러등유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.MOBILE_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("36.8"))
                .ncv(new BigDecimal("34.3"))
                .co2Factor(new BigDecimal("71900"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .mobileCo2Factor(new BigDecimal("71900"))
                .mobileCh4Factor(BigDecimal.ZERO)
                .mobileN2oFactor(BigDecimal.ZERO)
                .hasMobileFactors(true)
                .build());

        // 에탄
        saveFuelData(FuelData.builder()
                .fuelId("ETHANE")
                .fuelName("에탄")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("46.4"))
                .co2Factor(new BigDecimal("61600"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 나프타(납사)
        saveFuelData(FuelData.builder()
                .fuelId("NAPHTHA")
                .fuelName("나프타(납사)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("32.3"))
                .ncv(new BigDecimal("30.3"))
                .co2Factor(new BigDecimal("73300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 역청(아스팔트)
        saveFuelData(FuelData.builder()
                .fuelId("BITUMEN")
                .fuelName("역청(아스팔트)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("41.5"))
                .ncv(new BigDecimal("39.2"))
                .co2Factor(new BigDecimal("80700"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 윤활유
        saveFuelData(FuelData.builder()
                .fuelId("LUBRICANTS")
                .fuelName("윤활유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.MOBILE_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("39.8"))
                .ncv(new BigDecimal("37.0"))
                .co2Factor(new BigDecimal("73300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .mobileCo2Factor(new BigDecimal("73300"))
                .mobileCh4Factor(BigDecimal.ZERO)
                .mobileN2oFactor(BigDecimal.ZERO)
                .hasMobileFactors(true)
                .build());

        // 정유공장 원료(정제연료)
        saveFuelData(FuelData.builder()
                .fuelId("REFINERY_FEEDSTOCK")
                .fuelName("정유공장 원료(정제연료)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("43.0"))
                .co2Factor(new BigDecimal("73300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 정유가스(정제가스)
        saveFuelData(FuelData.builder()
                .fuelId("REFINERY_GAS")
                .fuelName("정유가스(정제가스)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("49.5"))
                .co2Factor(new BigDecimal("57600"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 접착제(파라핀왁스)
        saveFuelData(FuelData.builder()
                .fuelId("PARAFFIN_WAXES")
                .fuelName("접착제(파라핀왁스)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("40.2"))
                .co2Factor(new BigDecimal("73300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 백유(용제)
        saveFuelData(FuelData.builder()
                .fuelId("WHITE_SPIRIT")
                .fuelName("백유(용제)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("33.3"))
                .ncv(new BigDecimal("31.0"))
                .co2Factor(new BigDecimal("73300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // B-A유 (gcv 값 수정)
        saveFuelData(FuelData.builder()
                .fuelId("B_A_OIL")
                .fuelName("B-A유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("38.9"))
                .ncv(new BigDecimal("36.4"))
                .co2Factor(new BigDecimal("74100"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // B-B유 (gcv, ncv, co2Factor 수정)
        saveFuelData(FuelData.builder()
                .fuelId("B_B_OIL")
                .fuelName("B-B유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("40.5"))
                .ncv(new BigDecimal("38.0"))
                .co2Factor(new BigDecimal("77400"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // B-C유 (gcv, ncv 수정)
        saveFuelData(FuelData.builder()
                .fuelId("B_C_OIL")
                .fuelName("B-C유")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("41.6"))
                .ncv(new BigDecimal("39.2"))
                .co2Factor(new BigDecimal("77400"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 기타석유제품(기타)
        saveFuelData(FuelData.builder()
                .fuelId("OTHER_PETROLEUM_PRODUCTS")
                .fuelName("기타석유제품(기타)")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("40.2"))
                .co2Factor(new BigDecimal("73300"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 기타액체연료
        saveFuelData(FuelData.builder()
                .fuelId("OTHER_LIQUID_FUEL")
                .fuelName("기타액체연료")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(BigDecimal.ZERO) // 데이터 미제공
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // 부생연료 1호
        saveFuelData(FuelData.builder()
                .fuelId("BY_PRODUCT_FUEL_1")
                .fuelName("부생연료 1호")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("36.9"))
                .ncv(new BigDecimal("34.3"))
                .co2Factor(new BigDecimal("72000"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 부생연료 2호
        saveFuelData(FuelData.builder()
                .fuelId("BY_PRODUCT_FUEL_2")
                .fuelName("부생연료 2호")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("40.0"))
                .ncv(new BigDecimal("37.9"))
                .co2Factor(new BigDecimal("77000"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic( new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 바이오에탄올
        saveFuelData(FuelData.builder()
                .fuelId("BIOETHANOL")
                .fuelName("바이오에탄올")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .ncv(new BigDecimal("27.0"))
                .co2Factor(new BigDecimal("70800"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 바이오디젤
        saveFuelData(FuelData.builder()
                .fuelId("BIODIESEL")
                .fuelName("바이오디젤")
                .category(FuelCategory.LIQUID_PETROLEUM)
                .unit("kL")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.LIQUID)
                .gcv(new BigDecimal("38.53"))
                .ncv(new BigDecimal("27.0"))
                .co2Factor(new BigDecimal("70800"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing (new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());
    }

    // === 기체연료 생성 메서드 ===
    private void createGaseousFuels() {
        log.info("기체연료 데이터 생성 중...");
        
        // LPG (이동연소용)
        saveFuelData(FuelData.builder()
                .fuelId("LPG")
                .fuelName("액화석유가스(LPG)")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.MOBILE_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .gcv(new BigDecimal("62.8"))
                .ncv(new BigDecimal("57.7"))
                .co2Factor(new BigDecimal("63100"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .mobileCo2Factor(new BigDecimal("63100"))
                .mobileCh4Factor(new BigDecimal("62"))
                .mobileN2oFactor(new BigDecimal("0.2"))
                .hasMobileFactors(true)
                .build());

        // LNG (이동연소용 차량)
        saveFuelData(FuelData.builder()
                .fuelId("LNG_VEHICLE")
                .fuelName("LNG (차량용)")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.MOBILE_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .gcv(new BigDecimal("43.6"))
                .ncv(new BigDecimal("39.4"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .mobileCo2Factor(new BigDecimal("56100"))
                .mobileCh4Factor(new BigDecimal("92"))
                .mobileN2oFactor(new BigDecimal("3.0"))
                .hasMobileFactors(true)
                .build());

        // CNG (이동연소용 차량)
        saveFuelData(FuelData.builder()
                .fuelId("CNG_VEHICLE")
                .fuelName("CNG (차량용)")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.MOBILE_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .gcv(new BigDecimal("43.6"))
                .ncv(new BigDecimal("39.4"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .mobileCo2Factor(new BigDecimal("56100"))
                .mobileCh4Factor(new BigDecimal("92"))
                .mobileN2oFactor(new BigDecimal("3.0"))
                .hasMobileFactors(true)
                .build());

        // 천연가스(LNG) (고정연소용)
        saveFuelData(FuelData.builder()
                .fuelId("NATURAL_GAS")
                .fuelName("천연가스(LNG)")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .gcv(new BigDecimal("54.6"))
                .ncv(new BigDecimal("49.3"))
                .co2Factor(new BigDecimal("56100"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 코크스가스
        saveFuelData(FuelData.builder()
                .fuelId("COKE_OVEN_GAS")
                .fuelName("코크스가스")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .ncv(new BigDecimal("37.8"))
                .co2Factor(new BigDecimal("44400"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 고로가스
        saveFuelData(FuelData.builder()
                .fuelId("BLAST_FURNACE_GAS")
                .fuelName("고로가스")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .ncv(new BigDecimal("2.47"))
                .co2Factor(new BigDecimal("260000"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 전로가스
        saveFuelData(FuelData.builder()
                .fuelId("CONVERTER_GAS")
                .fuelName("전로가스")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .ncv(new BigDecimal("7.06"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // 도시가스 LNG (고정연소용)
        saveFuelData(FuelData.builder()
                .fuelId("CITY_GAS_LNG")
                .fuelName("도시가스(LNG)")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .gcv(new BigDecimal("43.6"))
                .ncv(new BigDecimal("39.4"))
                .co2Factor(new BigDecimal("56100"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 도시가스(LPG)
        saveFuelData(FuelData.builder()
                .fuelId("CITY_GAS_LPG")
                .fuelName("도시가스(LPG)")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .gcv(new BigDecimal("62.8"))
                .ncv(new BigDecimal("57.7"))
                .co2Factor(new BigDecimal("63100"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 기타 기체연료
        saveFuelData(FuelData.builder()
                .fuelId("OTHER_GAS_FUEL")
                .fuelName("기타 기체연료")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .ncv(BigDecimal.ZERO)
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // 매립지가스(LFG)
        saveFuelData(FuelData.builder()
                .fuelId("LANDFILL_GAS")
                .fuelName("매립지가스(LFG)")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .ncv(new BigDecimal("50.4"))
                .co2Factor(new BigDecimal("54600"))
                .ch4FactorEnergy(new BigDecimal("30"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 폐기물 유화/가스화 등
        saveFuelData(FuelData.builder()
                .fuelId("WASTE_GASIFICATION")
                .fuelName("폐기물 유화/가스화 등")
                .category(FuelCategory.GASEOUS_PETROLEUM)
                .unit("천㎥")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.GAS)
                .ncv(new BigDecimal("11.6"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());
    }

    // === 고체연료 생성 메서드 ===
    private void createSolidFuels() {
        log.info("고체연료 데이터 생성 중...");
        
        // 석유 코크스(석유코크)
        saveFuelData(FuelData.builder()
                .fuelId("PETROLEUM_COKE")
                .fuelName("석유 코크스(석유코크)")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("33.5"))
                .ncv(new BigDecimal("31.6"))
                .co2Factor(new BigDecimal("97500"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("3"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("10"))
                .n2oFactorEnergy(new BigDecimal("0.6"))
                .n2oFactorManufacturing(new BigDecimal("0.6"))
                .n2oFactorCommercial(new BigDecimal("0.6"))
                .n2oFactorDomestic(new BigDecimal("0.6"))
                .hasMobileFactors(false)
                .build());

        // 프로판
        saveFuelData(FuelData.builder()
                .fuelId("PROPANE")
                .fuelName("프로판")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("50.4"))
                .ncv(new BigDecimal("46.3"))
                .co2Factor(new BigDecimal("63100"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 부탄
        saveFuelData(FuelData.builder()
                .fuelId("BUTANE")
                .fuelName("부탄")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("49.6"))
                .ncv(new BigDecimal("45.6"))
                .co2Factor(new BigDecimal("63100"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 국내무연탄
        saveFuelData(FuelData.builder()
                .fuelId("DOMESTIC_ANTHRACITE")
                .fuelName("국내무연탄")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("18.9"))
                .ncv(new BigDecimal("18.6"))
                .co2Factor(new BigDecimal("98300"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("10"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("300"))
                .n2oFactorEnergy(new BigDecimal("1.5"))
                .n2oFactorManufacturing(new BigDecimal("1.5"))
                .n2oFactorCommercial(new BigDecimal("1.5"))
                .n2oFactorDomestic(new BigDecimal("1.5"))
                .hasMobileFactors(false)
                .build());

        // 수입무연탄
        saveFuelData(FuelData.builder()
                .fuelId("IMPORTED_ANTHRACITE")
                .fuelName("수입무연탄")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("24.7"))
                .ncv(new BigDecimal("24.4"))
                .co2Factor(new BigDecimal("98300"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("10"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("300"))
                .n2oFactorEnergy(new BigDecimal("1.5"))
                .n2oFactorManufacturing(new BigDecimal("1.5"))
                .n2oFactorCommercial(new BigDecimal("1.5"))
                .n2oFactorDomestic(new BigDecimal("1.5"))
                .hasMobileFactors(false)
                .build());

        // 원료용 유연탄
        saveFuelData(FuelData.builder()
                .fuelId("COKING_COAL")
                .fuelName("원료용 유연탄")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("29.3"))
                .ncv(new BigDecimal("28.2"))
                .co2Factor(new BigDecimal("94600"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("10"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("300"))
                .n2oFactorEnergy(new BigDecimal("1.5"))
                .n2oFactorManufacturing(new BigDecimal("1.5"))
                .n2oFactorCommercial(new BigDecimal("1.5"))
                .n2oFactorDomestic(new BigDecimal("1.5"))
                .hasMobileFactors(false)
                .build());

        // 연료용 유연탄 (기존 역청탄)
        saveFuelData(FuelData.builder()
                .fuelId("BITUMINOUS_COAL")
                .fuelName("연료용 유연탄")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("25.8"))
                .ncv(new BigDecimal("24.7"))
                .co2Factor(new BigDecimal("94600"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("10"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("300"))
                .n2oFactorEnergy(new BigDecimal("1.5"))
                .n2oFactorManufacturing(new BigDecimal("1.5"))
                .n2oFactorCommercial(new BigDecimal("1.5"))
                .n2oFactorDomestic(new BigDecimal("1.5"))
                .hasMobileFactors(false)
                .build());

        // 하위 역청탄(아역청탄)
        saveFuelData(FuelData.builder()
                .fuelId("SUB_BITUMINOUS_COAL")
                .fuelName("하위 역청탄(아역청탄)")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("22.7"))
                .ncv(new BigDecimal("21.4"))
                .co2Factor(new BigDecimal("96100"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("10"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("300"))
                .n2oFactorEnergy(new BigDecimal("1.5"))
                .n2oFactorManufacturing(new BigDecimal("1.5"))
                .n2oFactorCommercial(new BigDecimal("1.5"))
                .n2oFactorDomestic(new BigDecimal("1.5"))
                .hasMobileFactors(false)
                .build());

        // 갈탄
        saveFuelData(FuelData.builder()
                .fuelId("LIGNITE")
                .fuelName("갈탄")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(new BigDecimal("11.9"))
                .co2Factor(new BigDecimal("101000"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("10"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("300"))
                .n2oFactorEnergy(new BigDecimal("1.5"))
                .n2oFactorManufacturing(new BigDecimal("1.5"))
                .n2oFactorCommercial(new BigDecimal("1.5"))
                .n2oFactorDomestic(new BigDecimal("1.5"))
                .hasMobileFactors(false)
                .build());

        // 코크스
        saveFuelData(FuelData.builder()
                .fuelId("COKE_OVEN_COKE")
                .fuelName("코크스")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("29.1"))
                .ncv(new BigDecimal("28.9"))
                .co2Factor(new BigDecimal("107000"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("10"))
                .ch4FactorCommercial(new BigDecimal("10"))
                .ch4FactorDomestic(new BigDecimal("300"))
                .n2oFactorEnergy(new BigDecimal("1.5"))
                .n2oFactorManufacturing(new BigDecimal("1.5"))
                .n2oFactorCommercial(new BigDecimal("1.5"))
                .n2oFactorDomestic(new BigDecimal("1.5"))
                .hasMobileFactors(false)
                .build());

        // 기타 고체연료
        saveFuelData(FuelData.builder()
                .fuelId("OTHER_SOLID_FUEL")
                .fuelName("기타 고체연료")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(BigDecimal.ZERO)
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // LPG (차량용) - 고체 부문
        saveFuelData(FuelData.builder()
                .fuelId("LPG_VEHICLE")
                .fuelName("LPG (차량용)")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("63.6"))
                .ncv(new BigDecimal("58.4"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // 천연가스(LNG) - 고체 부문
        saveFuelData(FuelData.builder()
                .fuelId("LNG_SOLID")
                .fuelName("천연가스(LNG)")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .gcv(new BigDecimal("54.6"))
                .ncv(new BigDecimal("49.3"))
                .co2Factor(new BigDecimal("56100"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());
    }

    // === 기타 화석연료 생성 메서드 ===
    private void createOtherFossilFuels() {
        log.info("기타 화석연료 데이터 생성 중...");
        // 현재 별도 분류가 없으므로 비워둠
    }

    // === 바이오매스 생성 메서드 ===
    private void createBiomassFuels() {
        log.info("바이오매스 데이터 생성 중...");
        
        // 폐목재
        saveFuelData(FuelData.builder()
                .fuelId("WASTE_WOOD")
                .fuelName("폐목재")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(new BigDecimal("15.6"))
                .co2Factor(new BigDecimal("112000"))
                .ch4FactorEnergy(new BigDecimal("30"))
                .ch4FactorManufacturing(new BigDecimal("30"))
                .ch4FactorCommercial(new BigDecimal("300"))
                .ch4FactorDomestic(new BigDecimal("300"))
                .n2oFactorEnergy(new BigDecimal("4"))
                .n2oFactorManufacturing(new BigDecimal("4"))
                .n2oFactorCommercial(new BigDecimal("4"))
                .n2oFactorDomestic(new BigDecimal("4"))
                .hasMobileFactors(false)
                .build());

        // 바이오가스
        saveFuelData(FuelData.builder()
                .fuelId("BIOGAS")
                .fuelName("바이오가스")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(new BigDecimal("50.4"))
                .co2Factor(new BigDecimal("54600"))
                .ch4FactorEnergy(new BigDecimal("1"))
                .ch4FactorManufacturing(new BigDecimal("1"))
                .ch4FactorCommercial(new BigDecimal("5"))
                .ch4FactorDomestic(new BigDecimal("5"))
                .n2oFactorEnergy(new BigDecimal("0.1"))
                .n2oFactorManufacturing(new BigDecimal("0.1"))
                .n2oFactorCommercial(new BigDecimal("0.1"))
                .n2oFactorDomestic(new BigDecimal("0.1"))
                .hasMobileFactors(false)
                .build());

        // 땔감
        saveFuelData(FuelData.builder()
                .fuelId("FIREWOOD")
                .fuelName("땔감")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(new BigDecimal("15.6"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // 우드칩
        saveFuelData(FuelData.builder()
                .fuelId("WOOD_CHIPS")
                .fuelName("우드칩")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(new BigDecimal("15.6"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // 목탄
        saveFuelData(FuelData.builder()
                .fuelId("CHARCOAL")
                .fuelName("목탄")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(new BigDecimal("29.5"))
                .co2Factor(new BigDecimal("112000"))
                .ch4FactorEnergy(new BigDecimal("3"))
                .ch4FactorManufacturing(new BigDecimal("200"))
                .ch4FactorCommercial(new BigDecimal("200"))
                .ch4FactorDomestic(new BigDecimal("200"))
                .n2oFactorEnergy(new BigDecimal("4"))
                .n2oFactorManufacturing(new BigDecimal("1"))
                .n2oFactorCommercial(new BigDecimal("1"))
                .n2oFactorDomestic(new BigDecimal("1"))
                .hasMobileFactors(false)
                .build());

        // RDF
        saveFuelData(FuelData.builder()
                .fuelId("RDF")
                .fuelName("RDF")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(new BigDecimal("11.6"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // RPF
        saveFuelData(FuelData.builder()
                .fuelId("RPF")
                .fuelName("RPF")
                .category(FuelCategory.SOLID_PETROLEUM)
                .unit("톤")
                .emissionActivityType(EmissionActivityType.STATIONARY_COMBUSTION)
                .subcategoryType(SubcategoryType.SOLID)
                .ncv(new BigDecimal("11.6"))
                .co2Factor(BigDecimal.ZERO)
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());
    }

    // === 전력 데이터 생성 메서드 ===
    private void createElectricityData() {
        log.info("전력 데이터 생성 중...");
        
        // 전기
        saveFuelData(FuelData.builder()
                .fuelId("ELECTRICITY")
                .fuelName("전기")
                .category(FuelCategory.ENERGY)
                .unit("kWh")
                .emissionActivityType(EmissionActivityType.ELECTRICITY)
                .subcategoryType(SubcategoryType.ELECTRICITY)
                .ncv(new BigDecimal("9.6"))
                .co2Factor(new BigDecimal("0.4653"))
                .ch4FactorEnergy(new BigDecimal("0.0000054"))
                .ch4FactorManufacturing(new BigDecimal("0.0000054"))
                .ch4FactorCommercial(new BigDecimal("0.0000054"))
                .ch4FactorDomestic(new BigDecimal("0.0000054"))
                .n2oFactorEnergy(new BigDecimal("0.0000027"))
                .n2oFactorManufacturing(new BigDecimal("0.0000027"))
                .n2oFactorCommercial(new BigDecimal("0.0000027"))
                .n2oFactorDomestic(new BigDecimal("0.0000027"))
                .hasMobileFactors(false)
                .build());
    }

    // === 스팀 데이터 생성 메서드 ===
    private void createSteamData() {
        log.info("스팀 데이터 생성 중...");
        
        // 스팀 A타입
        saveFuelData(FuelData.builder()
                .fuelId("STEAM_A")
                .fuelName("스팀 A타입")
                .category(FuelCategory.ENERGY)
                .unit("GJ")
                .emissionActivityType(EmissionActivityType.STEAM)
                .subcategoryType(SubcategoryType.STEAM)
                .ncv(new BigDecimal("1"))
                .co2Factor(new BigDecimal("56.452"))
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // 스팀 B타입
        saveFuelData(FuelData.builder()
                .fuelId("STEAM_B")
                .fuelName("스팀 B타입")
                .category(FuelCategory.ENERGY)
                .unit("GJ")
                .emissionActivityType(EmissionActivityType.STEAM)
                .subcategoryType(SubcategoryType.STEAM)
                .ncv(new BigDecimal("1"))
                .co2Factor(new BigDecimal("60.974"))
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());

        // 스팀 C타입
        saveFuelData(FuelData.builder()
                .fuelId("STEAM_C")
                .fuelName("스팀 C타입")
                .category(FuelCategory.ENERGY)
                .unit("GJ")
                .emissionActivityType(EmissionActivityType.STEAM)
                .subcategoryType(SubcategoryType.STEAM)
                .ncv(new BigDecimal("1"))
                .co2Factor(new BigDecimal("59.685"))
                .ch4FactorEnergy(BigDecimal.ZERO)
                .ch4FactorManufacturing(BigDecimal.ZERO)
                .ch4FactorCommercial(BigDecimal.ZERO)
                .ch4FactorDomestic(BigDecimal.ZERO)
                .n2oFactorEnergy(BigDecimal.ZERO)
                .n2oFactorManufacturing(BigDecimal.ZERO)
                .n2oFactorCommercial(BigDecimal.ZERO)
                .n2oFactorDomestic(BigDecimal.ZERO)
                .hasMobileFactors(false)
                .build());
    }
}


